config:
  - ".github/**"
  - ".gitignore"
  - "setup.cfg"
  - "Makefile"

features:
  - "flake8_if_expr/*"

tests:
  - "tests/*"

documentation:
  - "README.md"

dependencies:
  - "poetry.lock"
  - "pyproject.toml"
