name: release-draft

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  generate-release-draft:
    runs-on: ubuntu-18.04

    steps:
    - name: Publish GITHUB release with changelog
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ github.ref }}
        version: ${{ github.ref }}
        publish: true
