name: verify-labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  run:
    runs-on: ubuntu-18.04

    steps:
      - uses: zwaldowski/match-label-action@v2
        with:
          allowed: >
            fix
            features
            documentation
            tests
            config
